export const NODE_TYPES = {
  FLOW_STEP: 'flowStep',
  BRANCH_CONTAINER: 'branchContainer',
  ADD_BUTTON: 'addButton',
};

export const EDGE_TYPES = {
  ADD_NODE_EDGE: 'addNodeEdge',
  BRANCH_SPLIT: 'branchSplit',
};

export const DIMENSIONS = {
  NODE_WIDTH: 300,
  NODE_HEIGHT: 80,
  ADD_BUTTON_WIDTH: 40,
  ADD_BUTTON_HEIGHT: 40,
  ADD_BUTTON_SIZE: 36,
  GRAPH_TOP_OFFSET: 40,
  NODE_SPACING: 40,
  BRANCH_HORIZONTAL_SPACING: 400,
  BRANCH_SPLIT_OFFSET: 40,
  MERGE_NODE_OFFSET: 40,
  EDGE_STROKE_WIDTH: 2,
  EDGE_STEP_OFFSET: 20,
  SCROLL_Y_MARGIN: 100,
};
