export const fields = [
  {
    label: 'Product Key',
    key: 'productKey',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Notes',
    key: 'notes',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Price',
    key: 'price',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Quantity',
    key: 'quantity',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Tax Rate 1',
    key: 'taxRate1',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Tax Name 1',
    key: 'taxName1',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Tax Rate 2',
    key: 'taxRate2',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Tax Name 2',
    key: 'taxName2',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Tax Rate 3',
    key: 'taxRate3',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Tax Name 3',
    key: 'taxName3',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Custom Value 1',
    key: 'customValue1',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Custom Value 2',
    key: 'customValue2',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Custom Value 3',
    key: 'customValue3',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
  {
    label: 'Custom Value 4',
    key: 'customValue4',
    type: 'string' as const,
    required: false,
    description: '',
    variables: true,
  },
];
