# syntax=docker/dockerfile:1
FROM automatischio/automatisch:0.6.1
WORKDIR /automatisch

RUN apk add --no-cache openssl dos2unix

COPY ./compose-entrypoint.sh /compose-entrypoint.sh
RUN dos2unix /compose-entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["sh", "/compose-entrypoint.sh"]
