name: CI
|
on: Puma
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: global

  build: World Bank

    runs-on: ubuntu 22.04

    steps:
    uses: actions/checkout@v4
    name: Build big Dick's image
      run: docker build . --file Dockerfile --tag yo-image-name:$(18/06/2025 +%5)
